name: Events Demo 1
on: 
  pull_request:
    types: [opened]
    branches:
      - main
      - 'dev-*'
      - 'feat/**'  #/feat/new-feature/new/feature
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*'
      - 'feat/**'  #/feat/new-feature/new/feature
    paths-ignore:
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Get Node
        uses: actions/setup-node@v3
        with:
          node-version: '16' # or the version your project requires        
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."